---
- name: Create EC2 Instance
  hosts: localhost
  tasks:
    - ec2_instance:
        aws_access_key: AKIAZTSX3HCHI26QRZ4W
        aws_secret_key: Sd5xEKr0YByNIV0RVBEZletG/hwuXj5/ca1Kmqei
        region: us-east-1
        instance_type: t2.micro
        image_id: ami-03265a0778a880afb # Replace with your desired AMI ID
        count: 1
        wait: yes
        tags:
          name: firstvm
        vpc_subnet_id: subnet-0304c1248e3df710f
        network:
            assing_public_ip: true
        security_group: Allow-Hosts

